import { useEffect, useState } from "react";
import { Link } from "wouter";
import { CalendarDays, Clock, Users } from "lucide-react";
import { supabase } from "@/lib/supabase";

type LiveClass = { id:string; slug:string; title:string; short_description:string; thumbnail_url:string|null; instructor:string; price_inr:number; timezone:string; live_course_sessions:{id:string;starts_at:string;ends_at:string}[] };
const date = (value:string) => new Intl.DateTimeFormat("en-IN", { dateStyle:"medium", timeStyle:"short", timeZone:"Asia/Kolkata" }).format(new Date(value));
export default function LiveClasses() {
  const [items,setItems]=useState<LiveClass[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{ document.title="Upcoming Live Classes | InfoKB"; if(!supabase){setLoading(false);return;} supabase.from("live_courses").select("id,slug,title,short_description,thumbnail_url,instructor,price_inr,timezone,live_course_sessions(id,starts_at,ends_at)").eq("status","published").eq("registration_open",true).then(({data})=>{ const next=(data??[]).map((x)=>({...x,live_course_sessions:(x.live_course_sessions??[]).filter((s)=>new Date(s.starts_at)>new Date()).sort((a,b)=>a.starts_at.localeCompare(b.starts_at))})).filter((x)=>x.live_course_sessions.length).sort((a,b)=>a.live_course_sessions[0].starts_at.localeCompare(b.live_course_sessions[0].starts_at)); setItems(next as LiveClass[]);setLoading(false);});},[]);
  return <main className="min-h-screen bg-background pt-20"><div className="bg-gradient-to-r from-[#003d6b] to-[#005B99] py-14 text-center text-white"><h1 className="text-4xl font-extrabold">Upcoming Live Classes</h1><p className="mt-3 text-white/75">Learn live with InfoKB experts.</p></div><section className="max-w-7xl mx-auto px-4 py-12">{loading?<p className="text-center text-muted-foreground">Loading live classes…</p>:items.length===0?<div className="rounded-2xl border p-12 text-center text-muted-foreground">No upcoming live classes at the moment. Please check back soon.</div>:<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{items.map((item)=>{const session=item.live_course_sessions[0];return <Link key={item.id} href={`/courses/live/${item.slug}`} className="overflow-hidden rounded-2xl border bg-card shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-44 bg-gradient-to-br from-[#003d6b] to-[#005B99]">{item.thumbnail_url&&<img src={item.thumbnail_url} alt="" className="h-full w-full object-cover"/>}</div><div className="p-5"><h2 className="font-bold">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.instructor}</p><p className="mt-3 line-clamp-2 text-sm text-muted-foreground">{item.short_description}</p><div className="mt-4 space-y-2 text-xs text-muted-foreground"><span className="flex gap-2"><CalendarDays className="h-4 w-4 text-primary"/>{date(session.starts_at)}</span><span className="flex gap-2"><Clock className="h-4 w-4 text-primary"/>{item.timezone}</span></div><div className="mt-5 flex justify-between font-semibold"><span>₹{Number(item.price_inr).toLocaleString("en-IN")}</span><span className="text-primary">View Course →</span></div></div></Link>})}</div>}</section></main>;
}
